services:
  frontend:
    container_name: frontend-dev
    build:
      dockerfile: dev.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./pages
        target: /app/pages
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./styles
        target: /app/styles
      - type: bind
        source: ./next-env.d.ts
        target: /app/next-env.d.ts
      - type: bind
        source: ./next.config.js
        target: /app/next.config.js
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json